//! Nomi italiani per la generazione procedurale.

/// First names (never with spaces: see `Npc::surname`).
pub(crate) const FEMALE_NAMES: &[&str] = &[
    "Anna",
    "Giulia",
    "Francesca",
    "Chiara",
    "Sara",
    "Martina",
    "Elena",
    "Valentina",
    "Federica",
    "Laura",
    "Paola",
    "Silvia",
    "Beatrice",
    "Alice",
    "Giorgia",
    "Ilaria",
    "Rosa",
    "Teresa",
    "Lucia",
    "Maria",
    "Caterina",
    "Agnese",
    "Bianca",
    "Irene",
    "Noemi",
    "Sofia",
    "Aurora",
    "Ginevra",
    "Emma",
    "Greta",
    "Marta",
    "Viola",
    "Camilla",
    "Nina",
    "Elisa",
    "Margherita",
    "Carla",
    "Adele",
    "Livia",
    "Ada",
];

pub(crate) const MALE_NAMES: &[&str] = &[
    "Marco",
    "Luca",
    "Matteo",
    "Alessandro",
    "Lorenzo",
    "Andrea",
    "Davide",
    "Simone",
    "Giovanni",
    "Stefano",
    "Riccardo",
    "Tommaso",
    "Pietro",
    "Filippo",
    "Emanuele",
    "Nicola",
    "Carlo",
    "Giuseppe",
    "Antonio",
    "Franco",
    "Salvatore",
    "Vittorio",
    "Enrico",
    "Bruno",
    "Ettore",
    "Leonardo",
    "Francesco",
    "Gabriele",
    "Edoardo",
    "Diego",
    "Samuele",
    "Michele",
    "Paolo",
    "Fabio",
    "Giacomo",
    "Mattia",
    "Elia",
    "Aldo",
    "Guido",
    "Dario",
];

pub(crate) const SURNAMES: &[&str] = &[
    "Rossi",
    "Russo",
    "Ferrari",
    "Esposito",
    "Bianchi",
    "Romano",
    "Colombo",
    "Ricci",
    "Marino",
    "Greco",
    "Bruno",
    "Gallo",
    "Conti",
    "De Luca",
    "Mancini",
    "Costa",
    "Giordano",
    "Rizzo",
    "Lombardi",
    "Moretti",
    "Barbieri",
    "Fontana",
    "Santoro",
    "Mariani",
    "Rinaldi",
    "Caruso",
    "Ferrara",
    "Galli",
    "Martini",
    "Leone",
    "Longo",
    "Gentile",
    "Martinelli",
    "Vitale",
    "Serra",
    "Coppola",
    "De Santis",
    "Marchetti",
    "Parisi",
    "Villa",
];

/// Names for carriages, by kind, used in order (with a numeric suffix when exhausted).
pub(crate) const DORM_NAMES: &[&str] = &["Alveare", "Cuccette Nord", "Le Brande", "Nido"];
pub(crate) const MENSA_NAMES: &[&str] = &["Il Refettorio", "Pentola Comune", "La Brace"];
pub(crate) const SERRA_NAMES: &[&str] = &["Giardino d'Inverno", "Orto Pensile", "La Vigna"];
pub(crate) const OFFICINA_NAMES: &[&str] = &["La Fucina", "Bullone", "Officina Grande"];
pub(crate) const MERCATO_NAMES: &[&str] = &["Il Bazar", "La Bottega", "Il Baratto"];

pub(crate) fn first_names(sex: crate::npc::Sex) -> &'static [&'static str] {
    match sex {
        crate::npc::Sex::Female => FEMALE_NAMES,
        crate::npc::Sex::Male => MALE_NAMES,
    }
}
