//! Nomi italiani per la generazione procedurale.

pub(crate) const FIRST_NAMES: &[&str] = &[
    "Anna",
    "Marco",
    "Giulia",
    "Luca",
    "Francesca",
    "Matteo",
    "Chiara",
    "Alessandro",
    "Sara",
    "Lorenzo",
    "Martina",
    "Andrea",
    "Elena",
    "Davide",
    "Valentina",
    "Simone",
    "Federica",
    "Giovanni",
    "Laura",
    "Stefano",
    "Paola",
    "Riccardo",
    "Silvia",
    "Tommaso",
    "Beatrice",
    "Pietro",
    "Alice",
    "Filippo",
    "Giorgia",
    "Emanuele",
    "Ilaria",
    "Nicola",
    "Rosa",
    "Carlo",
    "Teresa",
    "Giuseppe",
    "Lucia",
    "Antonio",
    "Maria",
    "Franco",
    "Caterina",
    "Salvatore",
    "Agnese",
    "Vittorio",
    "Bianca",
    "Enrico",
    "Irene",
    "Bruno",
    "Noemi",
    "Ettore",
];

pub(crate) const SURNAMES: &[&str] = &[
    "Rossi",
    "Russo",
    "Ferrari",
    "Esposito",
    "Bianchi",
    "Romano",
    "Colombo",
    "Ricci",
    "Marino",
    "Greco",
    "Bruno",
    "Gallo",
    "Conti",
    "De Luca",
    "Mancini",
    "Costa",
    "Giordano",
    "Rizzo",
    "Lombardi",
    "Moretti",
    "Barbieri",
    "Fontana",
    "Santoro",
    "Mariani",
    "Rinaldi",
    "Caruso",
    "Ferrara",
    "Galli",
    "Martini",
    "Leone",
    "Longo",
    "Gentile",
    "Martinelli",
    "Vitale",
    "Serra",
    "Coppola",
    "De Santis",
    "Marchetti",
    "Parisi",
    "Villa",
];

/// Names for carriages, by kind, used in order (with a numeric suffix when exhausted).
pub(crate) const DORM_NAMES: &[&str] = &["Alveare", "Cuccette Nord", "Le Brande", "Nido"];
pub(crate) const MENSA_NAMES: &[&str] = &["Il Refettorio", "Pentola Comune", "La Brace"];
pub(crate) const SERRA_NAMES: &[&str] = &["Giardino d'Inverno", "Orto Pensile", "La Vigna"];
pub(crate) const OFFICINA_NAMES: &[&str] = &["La Fucina", "Bullone", "Officina Grande"];
pub(crate) const MERCATO_NAMES: &[&str] = &["Il Bazar", "La Bottega", "Il Baratto"];
